Projects/blog_env/Scripts/Blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')), 
    path('', include('blogs.urls')),
    
]

Projects/blog_env/Scripts/accounts/urls.py
"""为应用程序accounts定义URL模式"""
from django.urls import path,include
from . import views

app_name='accounts'
urlpatterns = [
    # 包含默认的身份验证URL
    path('',include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register,name='register'),
]

Projects/blog_env/Scripts/blogs/urls.py
"""定义blogs的URL模式"""

from django.urls import path
from . import views

app_name='blogs'
urlpatterns = [
    # 主页
    path('',views.index,name='index'),
    # 显示所有主题的页面
    path('bloggers/',views.bloggers,name='bloggers'),
    # 具体博客界面
    path('bloggers/<int:blogger_id>',views.blogger,name='blogger'),
    # 用于添加新博客的网页
    path('new_blogger/',views.new_blogger,name='new_blogger'),
    # 用于添加新博文的页面
    path('new_blogpost/<int:blogger_id>/',views.new_blogpost,name='new_blogpost'),
    # 用于编辑条目的页面
    path('edit_blogpost/<int:blogpost_id>/',views.edit_blogpost,name='edit_blogpost'),
]

Projects/blog_env/Scripts/accounts/models.py
from django.db import models

# Create your models here.

Projects/blog_env/Scripts/blogs/models.py
from django.db import models

# Create your models here.
class Blogger(models.Model):
    """用户的博客"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text
    
class BlogPost(models.Model):
    """用户博客的具体博文内容"""
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'blogposts'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."

Projects/blog_env/Scripts/blogs/forms.py
from django import forms
from .models import Blogger,BlogPost


class BloggerForm(forms.ModelForm):
    class Meta:
        model = Blogger
        fields = ['text']
        labels = {'text': ''}
        

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Projects/blog_env/Scripts/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm



def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            login(request,new_user)
            return redirect('blogs:index')
        
    # 显示出空表单或者表单无效
    context = {'form':form}
    return render(request,'registration/register.html',context)

Projects/blog_env/Scripts/blogs/views.py
from django.shortcuts import render,redirect
from .models import Blogger,BlogPost
from .forms import BloggerForm,BlogPostForm

# Create your views here.
def index(request):
    """博客的主页"""
    return render(request,'blogs/index.html')

def bloggers(request):
    """显示所有博客"""
    bloggers = Blogger.objects.order_by('date_added')
    context = {'bloggers':bloggers}
    return render(request,'blogs/bloggers.html',context)

def blogger(request,blogger_id):
    """显示单篇博客及其所有的内容"""
    blogger = Blogger.objects.get(id=blogger_id)
    blogposts = blogger.blogpost_set.order_by('-date_added')
    context = {'blogger': blogger, 'blogposts': blogposts}
    return render(request, 'blogs/blogger.html', context)

def new_blogger(request):
    """添加新博客"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = BloggerForm()
    else:
        # POST提交的数据，对数据进行处理
        form = BloggerForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:bloggers')
        
    # 显示空表单或者指出表单数据无效
    context = {'form': form}
    return render(request, 'blogs/new_blogger.html', context)

def new_blogpost(request, blogger_id):
    """在特定的主题中添加新条目"""
    blogger = Blogger.objects.get(id=blogger_id)

    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = BlogPostForm()
    else:
        # POST提交的数据，对数据进行处理
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_blogpost = form.save(commit=False)
            new_blogpost.blogger = blogger
            new_blogpost.save()
            return redirect('blogs:blogger', blogger_id=blogger_id)
    #显示空表单或指出表单数据无效 
    context = {'blogger': blogger, 'form': form}
    return render(request, 'blogs/new_blogpost.html', context)

def edit_blogpost(request, blogpost_id):
    """编辑既有条目"""
    blogpost = BlogPost.objects.get(id=blogpost_id)
    blogger = blogpost.blogger

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = BlogPostForm(instance=blogpost)
    else:
        # POST提交的数据，对数据进行处理
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogger', blogger_id=blogger.id)
        
    context = {'blogpost': blogpost, 'blogger': blogger, 'form': form}
    return render(request, 'blogs/edit_blogpost.html', context)

Projects/blog_env/Scripts/blogs/templates/blogs/base.html
<!-- 父模板：此模板包含所有页面都有的元素，其他模板都要继承它 -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-o">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs:bloggers' %}">
                    Bloggers</a></li>
            </ul><!-- 定义导航栏左侧链接的代码到此结束 -->
            <!--与账户相关的链接 -->
            <ul class =" navbar-nav ms-auto mb-2 mb-md-o">
                {% if user.is_authenticated %}
                    <li class ="nav-item ">
                        <span class ="navbar-text me-2"> Hello ,{{ user.username }}.
                        </span ></ li >
                {% else %}
                    <li class ="nav-item">
                        <a class="nav-link" href ="{% url 'accounts:register'%}">
                            Register </a></li>
                    <li class="nav-item">
                        <a class ="nav-link" href ="{% url 'accounts:login' %}">
                            Log in </a></li>
                {% endif %}
            </ul><!--与账户相关的链接到此结束 -->
            {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button name='submit' class-'btn btn-outline-secondary btn-sm'>
                        Log out</button>
                    </form>
            {% endif %}       
        </div><!-- 定义导航栏可折叠部分的代码到此结束 -->
    </div><!-- 定义导航栏容器的代码到此结束 -->
</nav><!-- 定义导航栏的代码到此结束 -->

<main class="container">
    <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>
<!-- 定义导航栏的代码到此结束 -->

Projects/blog_env/Scripts/blogs/templates/blogs/blogger.html
{% extends 'blogs/base.html' %}
{% block page_header %}
    <h1>{{ blogger.text }}</h1>
{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'blogs:new_blogpost' blogger.id %}">Add new blogpost</a>
</p>

{% for blogpost in blogposts %}
    <div class="card mb-3">
    <!--包含时间戳和编辑链接的标题-->
    <h4 class="card-header">
    {{ blogpost.date_added|date:'M d,Y H:i'}}
    <small><a href= "{% url 'blogs:edit_blogpost' blogpost.id %}">
        edit blogpost</a></small>
    </h4>
    <!--包含条目文本的正文-->
    <div class="card-body">{{ blogpost.text|linebreaks }}</div>
    </div>
{% empty %}
    <p>There are no blogposts for this blogger yet.</p>
{% endfor %}
{% endblock content %}

Projects/blog_env/Scripts/blogs/templates/blogs/bloggers.html
{% extends 'blogs/base.html' %}
{% block page_header %}
    <h1>Bloggers</h1>
{% endblock page_header %}

{% block content %}
    <ul class="list-group border-bottom pb-2 mb-4">
        {% for blogger in bloggers %}
            <li class="list-group-item border-O">
                <a href= "{% url 'blogs:blogger' blogger.id %}">
                    {{blogger.text }}</a>
            </li>
        {% empty %}
            <li class="list-group-item border-O">No bloggers have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'blogs:new_blogger' %}">Add a new blogger</a>
{% endblock content %}

Projects/blog_env/Scripts/blogs/templates/blogs/edit_blogpost.html
{% extends "blogs/base.html" %}
{% block content %}
<p>
    <a href="{% url 'blogs:blogger' blogger.id %}">{{ blogger }}</a>
</p>
<p>Edit blogpost:</p>
<form action="{% url 'blogs:edit_blogpost' blogpost.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
</form>
{% endblock content %}

Projects/blog_env/Scripts/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Start to become a blogger!</h1>
            
            <p class="lead">Create your blogger and write down your first blogpost.</p>
            
            <a class="btn btn-primary btn-lg mt-1"
                href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

Projects/blog_env/Scripts/blogs/templates/blogs/new_blogger.html
{% extends "blogs/base.html" %}
{% block content %}
    <p>Add a new blogger:</p>
    <form action="{% url 'blogs:new_blogger' %}" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button name="submit">Add blogger</button>
    </form>
{% endblock content %}

Projects/blog_env/Scripts/blogs/templates/blogs/new_blogpost.html
{% extends "blogs/base.html" %}
{% block content %}
<p>
    <a href="{% url 'blogs:blogger' blogger.id %}">{{ blogger }}</a>
</p>
<p>Add a new blogpost:</p>
<form action="{% url 'blogs:new_blogpost' blogger.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Add blogpost</button>
</form>
{% endblock content %}